
# data_dir : "C:/Users/sar10/code/detr/cocodataset/"
data_dir : 'C:/Users/wolve/arsim/detr_git/DETR_pytorch/cocodataset/'
train_set : "val2017"   # "train2017"
# valid_set  : "val2017" 

batch_size : 16
learning_rate : 1.e-4
weight_decay : 1.e-4
num_epoch : 10
n_dim : 256
n_class : 81

backbone_params:
    n_channel : 256

tf_model_params:
    d_model: 256   # model Dimension
    # n_words: 800  # Total number of words
    drpoout_p: 0.2  # dropout rate 
    # max_len: 800   # Maximum length of input (one sentence)

    encoder_params:
      n_hidden: 2048
      # n_head: 8
      # n_iter: 10
      n_head: 4
      n_iter: 2

    decoder_params:
      n_hidden: 2048
      n_head: 4
      n_iter: 2
      activation: "gelu"
      x_shape: [1, 100, 256] # [batch, max of Obj cnt, d_model]