data :
  # data_dir : "C:/Users/sar10/code/detr/cocodataset/"
  data_dir : 'C:/Users/wolve/arsim/detr_git/DETR_pytorch/cocodataset/'
  train_set : "train2017"   # "train2017"
  # valid_set  : "val2017" 
  image_width : 320
  image_height : 320
  n_class : 81   # 80 : class 개수 + 1 (no object, background)
  max_boxes : 100  # same as 'n_obj' / Maximum number of objects in an image (y)

train_params:
  batch_size : 8
  learning_rate : 1.e-4
  weight_decay : 1.e-4
  num_epoch : 9999

backbone_params:
    n_channel : 256

tf_model_params:
    # n_dim : 128
    d_model: 256   # model Dimension
    drpoout_p: 0.2  # dropout rate 
    n_obj : 100   # Maximum number of objects
    # max_len: 800   # Maximum length of input (one sentence)

    encoder_params:
      n_hidden: 2048
      n_head: 8
      n_iter: 4

    decoder_params:
      n_hidden: 2048
      n_head: 8
      n_iter: 4
      activation: "gelu"
      # x_shape: [1, 100, 256] # [batch, max of Obj cnt, d_model]